### ISSUE TITLE
[BUG]side bar don't move

### ISSUE THREAD

**Issue by Fr-Dae** [MasonStooksbury/Infinite-Craft-Ingredient-Manager#1]
Firefox 128.0.1
lubuntu 22.04
i can't move the sidebar :/

**Comment by MasonStooksbury** [comment]
I don't think I'm quite sure what you mean. Do you have a screenshot perhaps?

The extension should just show a small popup next to the addon button (like in the README)

**Comment by Fr-Dae** [comment]
i"m on wrong github, sorry, have a nice day
